- name: Create Security Group For Redis
  ec2_group:
    name: "Redis-sg"
    description: "Security Group For Redis"
    region: "{{ region }}"
    state: present
    rules:
      - proto: tcp
        ports: "{{ redis_ports }}"
        # group_id: "{{ nodejs_sg.group_id }}" # Allow only backend
        cidr_ip: "{{ security_group_cidr_ingress }}"
    rules_egress:
      - proto: all
        cidr_ip: "{{ security_group_cidr_egress }}"
  register: redis_sg

- name: Launch Redis Instance
  ec2_instance:
    name: "Redis"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    wait: yes
    security_groups: ["{{ redis_sg.group_id }}"]
    key_name: "{{ key_name }}"
  register: redis_instance

- name: inspect redis_instance IP
  debug:
    var: redis_instance.instances[0].public_ip_address

- name: Add Redis Instance to Inventory
  add_host:
    name: redis
    ansible_host: "{{ redis_instance.instances[0].public_ip_address }}"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ key_path }}"