- name: Create Security Group For Frontend
  ec2_group:
    name: "React-sg"
    description: "Security Group For Reactjs Frontend"
    region: "{{ region }}"
    state: present
    rules:
      - proto: tcp
        ports: "{{ reactjs_ports }}"
        cidr_ip: "{{ security_group_cidr_ingress }}"
    rules_egress:
      - proto: all
        cidr_ip: "{{ security_group_cidr_egress }}"
  register: reactjs_sg

- name: Launch Frontend Instance
  ec2_instance:
    name: "Frontend"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    wait: yes
    security_groups: ["{{ reactjs_sg.group_id }}"]
    key_name: "{{ key_name }}"
  register: front_instance

- name: inspect front_instance IP
  debug:
    var: front_instance.instances[0].public_ip_address

- name: Add Frontend Instance to Inventory
  add_host:
    name: frontend
    ansible_host: "{{ front_instance.instances[0].public_ip_address }}"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ key_path }}"
